### ISSUE TITLE
conditional toggle?

### ISSUE THREAD

**Issue by KiaraGrouwstra** [wamserma/flake-programs-sqlite#22]
i've been using this module, but recently switched from channel `nixos-unstable-small` to `nixpkgs-unstable-small`.
this seemed to make the module throw errors, which i understand.
as a result i commented the module import now, but it would be nice if instead it would be possible to conditionally import it. i guess that seems a bit tricky tho - would there be a sensible way to detect whether one is using one type of channel over the other?

**Comment by wamserma** [comment]
`nixpkgs-unstable-small` is not available from `https://channels.nixos.org/`, so `flake-programs-sqlite` cannot obtain the `programs.sqlite` database. But you can tell it to use `nixos-unstable-small` while your system follows `nixpkgs-unstable-small`:

```nix
inputs.nixpkgs.url = github:NixOS/nixpkgs/nixpkgs-unstable-small;  # nixpkgs for your system, not a real channel
inputs.nixos-unstable.url = github:NixOS/nixpkgs/nixos-unstable-small;  # this branch has only commits that match the channel
inputs.flake-programs-sqlite = {
    url = "github:wamserma/flake-programs-sqlite";
    inputs.nixpkgs.follows = "nixos-unstable";  # the flake-programs-sqlite which "channel" to follow
};
```
