### ISSUE TITLE
"command-not-found itself is not enabled" error prevents building 

### ISSUE THREAD

**Issue by volkswagenfeature** [wamserma/flake-programs-sqlite#27]
Adding flake-programs-sqlite on line 70 [of my system config](https://github.com/volkswagenfeature/nix-sync/blob/7dc33d3f8e8b5c2466796643c15f55d86ac2ca03/nixos/flake.nix) fails with the error message below. I am on  NixOS 24.05, and using fish as my shell. What am I doing wrong?
```
error:
       … while calling the 'head' builtin

         at /nix/store/qszplw617r895nbcprgyj139c9a3r0xs-source/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/store/qszplw617r895nbcprgyj139c9a3r0xs-source/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error:
       Failed assertions:
       - Using programs.sqlite was requested but command-not-found itself is not enabled.
    ```

**Comment by wamserma** [comment]
I can see that you are also [using `nix-index`](https://github.com/volkswagenfeature/nix-sync/blob/7dc33d3f8e8b5c2466796643c15f55d86ac2ca03/nixos/mylibs/terminal.nix#L19) - please check if you have `programs.command-not-found.enable = false;` ([as suggested in the `nix-index` readme](https://github.com/nix-community/nix-index?tab=readme-ov-file#usage-as-a-command-not-found-replacement)) in your config. If so, re-enable it as requested by the error message.

**Comment by Andy3153** [comment]
I do not have `nix-index` enabled, and I am getting the error.

**Comment by wamserma** [comment]
> I do not have `nix-index` enabled, and I am getting the error.

Thank you for reporting this!

Upstream changed the default setting in https://github.com/NixOS/nixpkgs/commit/4241fb5eaeb33e8a673a547d1eb1bb2d3fc7d34f
so you now have to add 

```
programs.command-not-found.enable = true;
```

to your configuration.

I created https://github.com/wamserma/flake-programs-sqlite/issues/31 to keep track of this.
