### ISSUE TITLE
What is `command-not-found`

### ISSUE THREAD

**Issue by bburdette** [wamserma/flake-programs-sqlite#8]
Might be nice to have an explanation of what `command-not-found` is, in the readme, for those of us who have stumbled across this repo having never known this existed, but merely received its benefits as if by magic as a nixos user.  Such an explanation would make clear the motivation of this repo, and settle such questions as to whether this is nixos specific or what. 

Something like (not fact checked!): 

> `command-not-found` is a [perl script](nixos/modules/programs/command-not-found/command-not-found.pl) that resides in every nixos install.  If the user enters a command at the cli, and that command isn't installed on their system, `command-not-found` suggests nix packages that contain that command.  (How is is invoked?)   For instance without command-not-found you get this:
> 
> ```
> [bburdette@HOSS:~]$ dar
> dar: command not found
> ```
> 
> While a working command-not-found shows this:
> 
> ```
> [bburdette@HOSS:~]$ dar
> The program 'dar' is not in your PATH. You can make it available in an
> ephemeral shell by typing:
>   nix-shell -p dar
> ```

**Comment by wamserma** [comment]
@bburdette Would you mind reviewing https://github.com/wamserma/flake-programs-sqlite/pull/9?
